Repository ministryofjustice/hmpps-locations-inside-prison-api, pull requests merged in 2024-10, with the labels that each got.

#281 Reset the value for OTHER when changing to another type
  src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
  src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
Labels: bug

#293 MAP-1735 Upgrade dependencies
  build.gradle.kts
Labels: Dependency

#298 MAP-1761 Turn on Buckley Hall
  helm_deploy/values-prod.yaml
Labels: Don't Merge Yet!
